name: my first github action code
on: 
 push:
   branches: [main]
jobs:
  python_script:
     runs-on: ubuntu-latest
     steps:
       - name: code checkout
         uses: actions/checkout@v4

       - name: set up python
         uses: actions/setup-python@v5
         with:
           python-version: "3.11"

       - name: run the python script
         run: python add.py > output.txt

       - name: upload frile to artifactory
         uses: actions/upload-artifact@v4
         with:
           name: Output-file
           path: output.txt

  download-artifactory:
    needs: python_script
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/download-artifact@v4
        with:
           name: Output-file
      - run: cat output.txt
         

      


